# Example config for training model.

###
# General options
###
seed: 0
gpus: [1, 2, 3, 4]

###
# Data options
###
data_paths_config: 'data_paths.yaml'

# Points to keys in data_paths_config
train_split: 'train_val_split'
val_split: 'test_split'

# Number of labels
num_labels: 65

# Size to crop image to before passing to network.
crop_size: 224

# Mean pixel.
pixel_mean: [96.8293, 103.073, 101.662]

###
# Training options
###
# Number of total epochs to run.
num_epochs: 1000000
# Number of batches in epoch.
epoch_size: 250
# Specify epoch to start at (e.g. if we are continuing to train a model from
# earlier).
init_epoch: 1
# Number of examples in batch.
batch_size: 128
# One of 'permuted', 'balanced' (case-insensitive)
sampling_strategy: 'balanced'
sampling_strategy_options: {
    include_bg: False
}

###
# Optimization options
###
momentum: 0.9
weight_decay: 5.e-4

###
# Model options
###
# Lua model file.
# model_layout: './models/vgg_recurrent.lua'
# Torch model to start training with. If specified, model_layout is ignored.
model_init: '/data/achald/MultiTHUMOS/models/pretrained/vgg_pretrained_last_layer_updated/vgg16_ilsvrc_2014_pretrained_updated_for_multithumos.t7'
