# Example config for training model.

###
# General options
###
seed: 0
gpu: 3

###
# Data options
###
# LMDBs mapping keys to LabeledVideoFrames.
train_lmdb: '/data/achald/MultiTHUMOS/frames@10fps/labeled_video_frames/all_train.lmdb'
val_lmdb: '/data/achald/MultiTHUMOS/frames@10fps/labeled_video_frames/valval.lmdb'

# LMDBs mapping keys to LabeledVideoFrames, without image bytes. These LMDBs
# are quick to iterate over for sampling.
train_lmdb_without_images: '/data/achald/MultiTHUMOS/frames@10fps/labeled_video_frames/all_train_without_images.lmdb'
val_lmdb_without_images: '/data/achald/MultiTHUMOS/frames@10fps/labeled_video_frames/valval_without_images.lmdb'

# Number of labels
num_labels: 65

# Size to crop image to before passing to network.
crop_size: 224

# Mean pixel.
pixel_mean: [96.8293, 103.073, 101.662]

###
# Training options
###
# Number of total epochs to run.
num_epochs: 1000000
# Number of batches in epoch.
epoch_size: 500
# Specify epoch to start at (e.g. if we are continuing to train a model from
# earlier).
init_epoch: 1
# Number of examples in batch.
batch_size: 64
# One of 'permuted', 'balanced' (case-insensitive)
sampling_strategy: 'permuted'

###
# Optimization options
###
momentum: 0.9
weight_decay: 5.e-4

###
# Model options
###
# Lua model file.
model_layout: ''
# Torch model to start training with. If specified, model_layout can be omitted.
model_init: '/data/achald/MultiTHUMOS/models/vgg_pretrained_last_layer_updated/vgg16_ilsvrc_2014_pretrained_updated_for_multithumos.t7'
