# Example config for training model.

###
# General options
###
seed: 0
gpus: [1, 2, 3, 4]

###
# Data options
###
data_paths_config: 'config/local_data_paths.yaml'

# Points to keys in data_paths_config
train_split: 'train_split'
val_split: 'val_split'

# Number of labels
num_labels: 65

# Size to crop image to before passing to network.
crop_size: 224

# Mean pixel.
pixel_mean: [96.8293, 103.073, 101.662]

###
# Training options
###
# Number of total epochs to run.
num_epochs: 1000000
# Number of batches in epoch.
epoch_size: 250
# Specify epoch to start at (e.g. if we are continuing to train a model from
# earlier).
init_epoch: 1
# Number of examples in batch.
batch_size: 128
# One of 'permuted', 'balanced' (case-insensitive)
sampling_strategy: 'permuted'
sampling_strategy_options: {
}
sequence_length: 1

###
# Optimization options
###
momentum: 0.9
weight_decay: 5.e-4
learning_rates: [
    { start_epoch:  1,5learning_rate: 5.e-2 },
    { start_epoch:  6,5learning_rate: 5.e-3 },
    { start_epoch: 12,5learning_rate: 5.e-4 },
    { start_epoch: 18,5learning_rate: 5.e-5 },
    { start_epoch: 24,5learning_rate: 5.e-6 }
]

###
# Model options
###
# Lua model file.
# model_layout: './models/vgg_recurrent.lua'
# Torch model to start training with. If specified, model_layout is ignored.
model_init: '/data/achald/MultiTHUMOS/models/pretrained/resnet/resnet-50.t7'
