# Example config for training model.

###
# General options
###
seed: 0
gpus: [1, 2, 3, 4]

###
# Data options
###
data_paths_config: 'config/local_data_paths.yaml'

# Points to keys in data_paths_config
train_split: 'train_split'
val_split: 'val_split'

# Number of labels
num_labels: 65

# Size to crop image to before passing to network.
crop_size: 224

# Mean pixel.
pixel_mean: [96.8293, 103.073, 101.662]

###
# Training options
###
# Number of total epochs to run.
num_epochs: 1000000
# Number of batches in epoch.
epoch_size: 500
# Specify epoch to start at (e.g. if we are continuing to train a model from
# earlier).
init_epoch: 1
# Number of examples in batch. This is how many examples we use to compute
# a gradient update.
batch_size: 50
# The computational batch size. This is how many examples we forward/backward at
# a time computationally. Must evenly divide batch_size.
computational_batch_size: 30
val_batch_size: 30
val_epoch_size: 800
criterion_wrapper: 'sequencer_criterion'

# One of 'permuted', 'balanced' (case-insensitive)
sampling_strategy: 'balanced'
sampling_strategy_options: {
    include_bg: True
}
sequence_length: 4

###
# Optimization options
###
momentum: 0.9
weight_decay: 5.e-4
learning_rates: [
    { start_epoch:  1, learning_rate: 1.e-2 },
    { start_epoch: 11, learning_rate: 1.e-3 },
    { start_epoch: 21, learning_rate: 1.e-4 },
    { start_epoch: 31, learning_rate: 1.e-5 },
    { start_epoch: 41, learning_rate: 1.e-6 }
]

###
# Model options
###
# Torch model to start training with.
model_init: '/data/achald/MultiTHUMOS/models/permuted_sampling_vgg/model_30_pyramid_seq4_start_avg_at_conv4_3_scalar_learned_weights.t7'
