# Config for training C3D.
# Hyperparameters copied from S-CNN:
#   https://github.com/zhengshou/scnn/blob/726fe5e22bafa74372b680e283bb1098a4d3315e/experiments/THUMOS14/network_classification/solver.prototxt
#   https://github.com/zhengshou/scnn/blob/726fe5e22bafa74372b680e283bb1098a4d3315e/experiments/THUMOS14/network_classification/train.prototxt

###
# General options
###
seed: 0
gpus: [1, 2, 3, 4]

###
# Data options
###
data_paths_config: 'config/local_data_paths.yaml'

# Points to keys in data_paths_config
train_split: 'train_split'
val_split: 'val_split'

# Number of labels
num_labels: 65

# Size to crop image to before passing to network.
crop_size: 112

# Mean pixel.
pixel_mean: [96.8293, 103.073, 101.662]

###
# Training options
###
# Number of total epochs to run.
num_epochs: 80
# Number of batches in epoch.
epoch_size: 500
# Specify epoch to start at (e.g. if we are continuing to train a model from
# earlier).
init_epoch: 1
# Number of examples in batch.
batch_size: 30
# One of 'permuted', 'balanced' (case-insensitive)
sampling_strategy: 'balanced'
sampling_strategy_options: {
    include_bg: False
}
sequence_length: 16
use_boundary_frames: True

###
# Optimization options
###
momentum: 0.9
weight_decay: 5.e-4
learning_rates: [
    { start_epoch:  1, learning_rate: 1.e-4 },
    { start_epoch: 11, learning_rate: 1.e-5 },
    { start_epoch: 21, learning_rate: 1.e-6 },
    { start_epoch: 31, learning_rate: 1.e-7 },
    { start_epoch: 41, learning_rate: 1.e-8 },
]

###
# Model options
###
# Torch model to start training with.
model_init: '/data/achald/MultiTHUMOS/models/pretrained/c3d_pretrained/c3d_multithumos.t7'

# Specifies what each dimension in the input tensor corresponds to.
# By default, the input dimension order is
#   (sequence_length, batch_size, num_channels, width, height)
# A permutation of [2, 3, 1, 4, 5], as for C3D, results in
#   (batch_size, num_channels, sequence_length, width, height)
input_dimension_permutation: [2, 3, 1, 4, 5]
