# Paths for LMDBs mapping keys to LabeledVideoFrames.
train_split:
    with_images:    '/scratch/achald/all_train.lmdb'
    without_images: '/scratch/achald/all_train_without_images.lmdb'

# Subset of train split that contains only the THUMOS val videos.
train_split_val_subset:
    with_images:    '/scratch/achald/valtrain.lmdb'
    without_images: '/scratch/achald/valtrain_without_images.lmdb'

val_split:
    with_images:    '/scratch/achald/valval.lmdb'
    without_images: '/scratch/achald/valval_without_images.lmdb'

# train_split and val_split combined
train_val_split:
    with_images:    '/scratch/achald/all_train_and_val.lmdb'
    without_images: '/scratch/achald/all_train_and_val_without_images.lmdb'

test_split:
    with_images:    '/scratch/achald/test.lmdb'
    without_images: '/scratch/achald/test_without_images.lmdb'
